services:
  api:
    build: .
    environment: 
     - ASPNETCORE_URLS=http://+8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coldharbourdb
    ports:
      - "5432:5432"
