services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - frontend
      - api

  frontend:
    build: ./ColdHarbourFrontend/

  api:
    build: ./ColdHarbourBackend/
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coldharbourdb
    ports:
      - "5432:5432"

