version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Expose port 80 for the reverse proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api

  frontend:
    build: ./ColdHarbourFrontend/
    ports:
      - "4000:80" # Angular app runs on port 80 internally, exposed as 4000 for debugging
    depends_on:
      - api

  api:
    build: ./ColdHarbourBackend/
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coldharbourdb
    ports:
      - "5432:5432"
